coverage:
  status:
    project:
      default:
        target: "95%"
        threshold: "0%"
    patch:
      default:
        target: "95%"
        threshold: "0%"

ignore:
  - "dist/**"
  - "scripts/**"
  - "test/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"
